name: Testing action to create PR

on:
  push:
    branches:
      - feature/some-feature

jobs:
  create-pr-against-master-job:
    runs-on: ubuntu-latest
    name: create PR
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - run: exit 0
      - name: Create PR
        uses: poorva17/create-pr-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: development
          HEAD_BRANCH: feature/some-feature
